- date: "2026.09.07"
  type: activity
  text: "The IABSE TG1.16 has officially started with a successful online kick-off meeting! Thanks all members!"

- date: "2026.08.27"
  type: activity
  text: "I have talked at SMAR2026, Dresden on 'how much we can trust acoustic emission in the field'."
  
- date: "2026.07.23"
  type: activity
  text: "I have talked at FUTUREROADS Conference, Cambridge on 'Modeling pavement deterioration using Bayesian Network'."

- date: "2026.09-present"
  type: service
  text: "Chair of *IABSE TG1.16* (https://www.iabse.org/C1)."

- date: "2024.09-present"
  type: service
  text: "Member of *fib TG1.1* (https://www.fib-international.org/commissions/com1-concrete-structures.html)."

- date: "2024.09-present"
  type: service
  text: "Member of *RILEM 328-QPA* (https://www.rilem.net/groupe/328-qpa-quality-and-performance-assurance-of-additively-manufactured-cementitious-composites-by-advanced-non-invasive-techniques-467/page/documents)."
