- date: "2026.09-present"
  type: service
  text: "Chair of *IABSE TG1.16* (https://www.iabse.org/C1)."

- date: "2024.09-present"
  type: service
  text: "Member of *fib TG1.1* (https://www.fib-international.org/commissions/com1-concrete-structures.html)."

- date: "2024.09-present"
  type: service
  text: "Member of *RILEM 328-QPA* (https://www.rilem.net/groupe/328-qpa-quality-and-performance-assurance-of-additively-manufactured-cementitious-composites-by-advanced-non-invasive-techniques-467/page/documents)."
